[workspace]
members = [
    "nmk_archs",
    "nmk_drivers",
    "nmk_utils",
    "nmk_status",
    "nonamekernel",
]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
