[build]
jobs = 4
target-dir = "build"
target = "./.cargo/target.json"
rustflags = "-C link-arg=-nostartfiles"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]