[build]
jobs = 4
target-dir = "build"
target = "./.cargo/target.json"
rustflags = "-C link-arg=-nostartfiles"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[package.metadata.bootimage]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}"]
build-command = ["build"]